# Required, name of the template
name = "Atari 2600 ca65 Template"

# Optional, longer form description
description = "A template for Atari 2600."

# Required, the version of the kickstart schema, currently only `1` is used
kickstart_version = 1

# Optional, a list of authors for this template
authors = [

]
# Optional, a list of keywords for this template
keywords = [

]
# Optional, those files will NOT be copied over when generating the template
# Use it to remove template-specific like its CI or its README/docs
# ignore = [
#     "README.md",
#     "CONTRIBUTING.md",
#     "CODE_OF_CONDUCT.md",
#     "docs",
# ]

directory = "{{project_name}}"

# Optional, a list of patterns. All files matching one of the patterns will
# be copied over without going through Tera.

# A list of variables, the schema is explained in detail below
[[variables]]
name = "project_name"
default = "my-project"
prompt = "What is the name of this project?"
validation = "^([a-zA-Z][a-zA-Z0-9_-]+)$"

[[variables]]
name = "rom_size"
default = "4096"
prompt = "Which ROM size do you want to use?"
choices = ["2048", "4096"]

