set(CMAKE_SYSTEM_NAME Generic)

set(CMAKE_ASM_COMPILER ca65 CACHE PATH "${lang} compiler")
set(CMAKE_ASM_COMPILER_ID ca65 )

set(CMAKE_LINKER ld65 CACHE PATH "${lang} linker")
set(CMAKE_LINKER_ID ld65)

set(CMAKE_ASM_OUTPUT_EXTENSION ".o")
set(CMAKE_ASM_OUTPUT_EXTENSION_REPLACE 1)

set(CMAKE_ASM_COMPILE_OBJECT "<CMAKE_ASM_COMPILER> <INCLUDES> <FLAGS> -o <OBJECT> <SOURCE>")

find_program(CMAKE_AR ar65)

set(CMAKE_ASM_CREATE_STATIC_LIBRARY 
    "<CMAKE_COMMAND> -E remove <TARGET>" 
    "<CMAKE_AR> a <TARGET> <LINK_FLAGS> <OBJECTS>")

set(CMAKE_ASM_LINK_EXECUTABLE "<CMAKE_LINKER> -o <TARGET> <LINK_FLAGS> <OBJECTS>")

